exclude_paths:
 - static/js/jquery.js
 - static/js/jquery.nicescroll.js
 - static/js/chart-master/Chart.js
 - static/css/style-responsive.css
 - static/js/jquery.tagsinput.js
 - static/gritter/js/jquery.gritter.js
 - static/font-awesome/css/font-awesome.css
 - static/js/bootstrap-switch.js
 - static/js/js.cookie.js
 - static/gritter/css/jquery.gritter.css
 - static/js/bootstrap.min.js
 - static/js/jquery-ui-1.9.2.custom.min.js
 - static/js/jquery.ui.touch-punch.min.js
